---
- name: copy apache configuration file
  copy: src=files/apache2.conf dest=/etc/apache2/apache2.conf
- name: copy index.html file
  copy: src=files/index.html dest=/var/www/html
  notify:
    - restart apache2

